In [1]:
import numpy as np

In [2]:
# 0D tensor 

a = np.array(4)

In [3]:
# print the value of tensor
a

array(4)

In [4]:
# finding the dimention of the tensor
a.ndim

0

In [6]:
# 1D tensor or vector, 1 D array there will be one axis or rand will be 1, but it call is Vector then dimension of the vector will be number of element present in the list ex- l = [1,2,3,4] for tensor dimension is one but for vector dimension is 4.

arr = np.array([1,2,3,4])

In [7]:
# printing the array
arr

array([1, 2, 3, 4])

In [9]:
# Printing the dimantion of tensor
arr.ndim

1

In [10]:
# 2D tensor or Matrix

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mat.ndim

2

In [14]:
# Create a 3D tensor with dummy values
tensor = np.zeros((2, 3, 4))

print(tensor)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
